apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - image: {{ .Values.appimage}}:{{ .Values.apptag}}
        name: product-service
        ports: 
        - containerPort: 8080
          name: product-port
      #   volumeMounts:
      #   - name: persistent-storage
      #     mountPath: "/var/product-servicemnt"
      # volumes:
      # - name: persistent-storage
      #   persistentVolumeClaim:
      #     claimName: pvc-efs
