name: Product-Service
on: workflow_dispatch
#on: [push, workflow_dispatch]
env:
  CODE_DIR: products-service
jobs:
  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.CODE_DIR }}

    steps:
      - name: Code checkout 
        uses: actions/checkout@v4

      - name: Maven test 
        run: mvn test 

      - name: Checkstyle
        run: mvn checkstyle:checkstyle 

 # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
    # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
    # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
             -Dsonar.host.url=https://sonarcloud.io
             -Dsonar.login=07d772e3f32bbafb5a010e1a6de2ded247c9891d
             -Dsonar.organization=cascompany
             -Dsonar.projectKey=project-Product-Service
             -Dsonar.sources=src/
             -Dsonar,junit.reportsPath=target/checckstyle-result.xml
             -Dsonar,jacoco.reportsPath0tarjet/jacoco.exec
             -Dsonar.java.checkstyle.reportPath=target/checkstyle-result.xml
             -Dsonar.java.binaries=target/test-classes/com/visualpathit/account
  #          -Dsonar.sources=$GITHUB_WORKSPACE          

