name: Product-Service
on: workflow_dispatch
env:
  CODE_DIR: './products-service'
jobs:
  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.CODE_DIR }}

    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODE_DIR }}

      - name: Maven test 
        run: mvn test 

      - name: Checkstyle
        run: mvn checkstyle:checkstyle 

