name: Product-Service
on: workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'products-service'

    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
        with:
          path: 'products-service'

      - name: Maven test 
        run: mvn test 

      - name: Checkstyle
        run: mvn checkstyle:checkstyle 

