name: Product-Service
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
        with:
          path: 'products-service'

      - name: Maven test 
        run: mvn  test 

      - name: Checkstyle
        run: |
          cd products-service/
          mvn checkstyle:checkstyle 

